helm:
  parameters:
  - name: env.nextPublicBackendUrl
    value: https://dev.api.laurimaila.com
    forcestring: false
  - name: env.nextPublicBaseUrl
    value: https://dev.laurimaila.com
    forcestring: false
  - name: image.repository
    value: ghcr.io/laurimaila/physics-svc
    forcestring: true
  - name: image.tag
    value: dev@sha256:0d19a1256395462b4b75727b61c95a59e6d50eacde37c618db74482872816888
    forcestring: true
  - name: ingress.cors.allowOrigin
    value: https://dev.laurimaila.com
    forcestring: false
  - name: ingress.host
    value: .laurimaila.com
    forcestring: false
  - name: ingress.tls.secretName
    value: physics-svc-tls-dev
    forcestring: false
  - name: jwt.existingSecret
    value: personal-website-dev-secrets
    forcestring: false
  - name: physicsService.host
    value: physics-svc
    forcestring: false
  - name: postgres.existingSecret
    value: personal-website-dev-secrets
    forcestring: false
  - name: postgres.host
    value: postgres.postgres.svc.cluster.local
    forcestring: false
