apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: personal-website-secrets
  namespace: personal-website
spec:
  refreshInterval: "3h"
  secretStoreRef:
    name: oci-vault-store
    kind: ClusterSecretStore
  target:
    name: personal-website-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: personal-website-prod-secrets
