apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: personal-website-apps
  namespace: argocd
spec:
  generators:
    # Production
    - matrix:
        generators:
          - list:
              elements:
                - branch: main
                  namespace: personal-website
                  suffix: ""
                  frontendSubdomain: "prod"
          - list:
              elements:
                - component: backend
                  imageName: ghcr.io/laurimaila/backend-personal-website
                  updateStrategy: semver
                  allowTags: "regexp:^[0-9]+\\.[0-9]+\\.[0-9]+$"
                  ingressSubdomain: "prod.api"
                - component: frontend
                  imageName: ghcr.io/laurimaila/personal-website
                  updateStrategy: semver
                  allowTags: "regexp:^[0-9]+\\.[0-9]+\\.[0-9]+$"
                  ingressSubdomain: "prod"
                - component: physics-svc
                  imageName: ghcr.io/laurimaila/physics-svc
                  updateStrategy: semver
                  allowTags: "regexp:^[0-9]+\\.[0-9]+\\.[0-9]+$"
                  ingressSubdomain: ""
                - component: migration-svc
                  imageName: ghcr.io/laurimaila/liquibase-svc
                  updateStrategy: semver
                  allowTags: "regexp:^[0-9]+\\.[0-9]+\\.[0-9]+$"
                  ingressSubdomain: ""
    # Dev
    - matrix:
        generators:
          - list:
              elements:
                - branch: dev
                  namespace: personal-website-dev
                  suffix: "-dev"
                  frontendSubdomain: "dev"
          - list:
              elements:
                - component: backend
                  imageName: ghcr.io/laurimaila/backend-personal-website:dev
                  updateStrategy: digest
                  allowTags: ".*"
                  ingressSubdomain: "dev.api"
                - component: frontend
                  imageName: ghcr.io/laurimaila/personal-website:dev
                  updateStrategy: digest
                  allowTags: ".*"
                  ingressSubdomain: "dev"
                - component: physics-svc
                  imageName: ghcr.io/laurimaila/physics-svc:dev
                  updateStrategy: digest
                  allowTags: ".*"
                  ingressSubdomain: ""
                - component: migration-svc
                  imageName: ghcr.io/laurimaila/liquibase-svc:dev
                  updateStrategy: digest
                  allowTags: ".*"
                  ingressSubdomain: ""
  template:
    metadata:
      name: "personal-website-{{component}}{{suffix}}"
      namespace: argocd
      annotations:
        argocd-image-updater.argoproj.io/image-list: "{{component}}={{imageName}}"
        argocd-image-updater.argoproj.io/{{component}}.update-strategy: "{{updateStrategy}}"
        argocd-image-updater.argoproj.io/{{component}}.allow-tags: "{{allowTags}}"
        argocd-image-updater.argoproj.io/write-back-method: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/laurimaila/argocd-personal-website.git
        targetRevision: "{{branch}}"
        path: "charts/{{component}}"
        helm:
          parameters:
            - name: ingress.host
              value: "{{ingressSubdomain}}.laurimaila.com"
            - name: ingress.cors.allowOrigin
              value: "https://{{frontendSubdomain}}.laurimaila.com"
            - name: postgres.host
              value: "postgres.postgres.svc.cluster.local"
            - name: physicsService.host
              value: "physics-svc"
            - name: ingress.tls.secretName
              value: "{{component}}-tls{{suffix}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
