apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: personal-website-secrets
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: prod
            namespace: personal-website
            path: personal-website/secrets/prod
  template:
    metadata:
      name: "personal-website-{{env}}-secrets"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/laurimaila/argocd-personal-website.git
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
