image:
  repository: ghcr.io/laurimaila/backend-personal-website
  tag: "1.6.0"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: regcred

postgres:
  host: postgres.postgres.svc.cluster.local
  existingSecret: "postgres-secret"
  secretKeys:
    userKey: POSTGRES_USER
    passwordKey: POSTGRES_PASSWORD
    dbKey: POSTGRES_DB

jwt:
  existingSecret: "backend-secrets"
  secretKey: JWT_SECRET_KEY

ingress:
  enabled: true
  className: traefik
  host: prod.api.laurimaila.com
  cors:
    allowOrigin: "https://prod.laurimaila.com"
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: leresolver

physicsService:
  host: "physics-svc"
  port: "50051"

resources:
  requests:
    memory: "256Mi"
    cpu: "200m"
  limits:
    memory: "512Mi"
    cpu: "500m"
