---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-sealed-secret
  namespace: logging
spec:
  encryptedData:
    admin-password: AgAEUszVGcM2Do2sjK2C0fiY2a0ePswkhD3CQOPPRkkbkMrmsA+74mKMLkiHvOKKHWE8dd/qVhGAItDPD2dd8A9LKS5aJwZm0hrEpX0SYFJX2jv8VHb6TAIeeYJn4JYjtAEtaI0CldqQMGqrNXFuIiLyecWV8rQqWEsXZfCmGZvLidpEc+k4cZ1utE/Gp/znXdcss4ULL1rp1BrJxhOpHRueV6iHoctKtgujgqBccKFgckjZMa47FIkUxjlTq2hLXX4Q7fuoL6GuFW1q9cjVSCJo/izyBKfee4JHctQokhSvbGGpYwLpq03dBJ5seG8bXHJYTfMfcjsh/XZnJkfpDQ8X6eFclVtdoTcFbzV2nQ3uyjEqq+KQrjNInBEtOsf3/zaKGvMqaC6nlPX9yRw6SmQ5SxbS+hKSHhbdtHRVMWpN0+bRqjmzXIXCOOdjZ7QgeaR2x2S1pBAaoNp3uc5HLAWA8kEF/L5aDWTx3APw+e9EHcWHxitoUt56vNlMIhixXQwCkGFrKYCDQiGCwZMq7Z2QIPfJG2IO1Gpf0U37m4HyoRM598Po45rHbws1CROS8rQInYQqfHxR25QRsm3sph+S10Rlzlh6WcDKGbedUpkvfeFVf/5vfuGqlFEz7xREe+LA6Mt0NuQZfOBZrKhJhG+wMTMoYXNxycVSbWFjdvb0KTY6OJkHVnDXhrgXNF218RbS8qjJaobiIEnfpzIPEb9VEuJKhgxTsAdIH6vHBzKXnwEyuAiW1kFB
    admin-user: AgBG7NyJwoXorHJc1lbprYJYiv37yzti03kptSO+mO4MU36pqXRwVaqp++T4J5a/bUC4B96tDB6W5WRE81V203mdXCWTZ23Vv+652pyQKIsK/IDJB5hh3iCCNOxZU37TFYxQpJ13mwRIOOpY20/c/efFnNImP8ZJ8Ka8/+iiqgB3tKlSGWwclIG5eyxIG2evtbxhx5rgj024iDCvxfjxDD+6Vt79Z6IpypTAFmrUE6avQ+zMbbEss7DVhD4xdMoBXBH0nJoqjez6fcT8HKEY5NNjzkwhLgMvOiIErT+JPdc46jaPDd97hbib+e4Rmnhp9UFqVOtbJqZQ2N5Lgymid9pFIX4n5hcyfm0+beIYdbtsgrpt+hbxj0Nh8wHCa/1AOMXdmBzLsvwZnsyTewyYzRJW3XUwNldyNYbqPTylknKG7gXdZC9Jnfj7XhSoIQ7gP4ZlQ21sdpKrvNqMjemdS5TGnq1WMehkTrLZJIrLfGaV8hFnxqDyweABE78HoXTg8tpPQDPSDsm7Wov69Uc5Ux/QAgqn/+E+x7dPLGUCigmp8TbdEtBOP1ZABumDnJ6jIyGzCrO8UjjCNMCALOon3UneFwmNlFWEl6THQTCYt5h6N6ISPHAFQhxzNVPlpuLp66KEeaAPL/FZTreSAK22ip7Tc3cuEEzdy7m5IwvLVpKTP+kG+lsVLRMfJ8Y7y6kD/T5KCt0eFg==
  template:
    metadata:
      name: grafana-sealed-secret
      namespace: logging
