deploymentMode: SingleBinary
loki:
  commonConfig:
    replication_factor: 1
  auth_enabled: false
  storage:
    type: filesystem
  limits_config:
    retention_period: 3d
  compactor:
    working_directory: /var/loki/compactor
    compaction_interval: 10m
    retention_enabled: true
    retention_delete_delay: 2h
    retention_delete_worker_count: 10
    delete_request_store: filesystem
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h
chunksCache:
  enabled: false
resultsCache:
  enabled: false
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 2Gi
  resources:
    limits:
      cpu: 500m
      memory: 768Mi
    requests:
      cpu: 50m
      memory: 256Mi
read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0
